name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    - name: Clone pylint threshold script
      run: |
        git clone https://gist.github.com/08de8563d24c9836689a58baf6097316.git
        mv 08de8563d24c9836689a58baf6097316/lint.py .
    - name: Analysing the code with pylint
      run: |
        python lint.py --path development --path tests --threshold 9.5
